First I import numpy, pandas,  and read in the csv file
as df for dataframe

In [2]:
import numpy as np
import pandas as pa

df = pa.read_csv("student_dataV2.csv")

I call upon the df function to see the first 5 and last 5 records

In [3]:
df

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17.0,5.0,171.0,1,1,122.0,1,19,12.0,...,0,0.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15.0,1.0,9254.0,1,1,160.0,1,1,3.0,...,0,6.0,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1.0,5.0,9070.0,1,1,122.0,1,37,37.0,...,0,6.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17.0,2.0,9773.0,1,1,122.0,1,38,37.0,...,0,6.0,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39.0,1.0,8014.0,0,1,100.0,1,37,38.0,...,0,6.0,6,6,13.000000,0,13.9,-0.3,0.79,Graduate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4419,1,1.0,6.0,9773.0,1,1,125.0,1,1,1.0,...,0,6.0,8,5,12.666667,0,15.5,2.8,-4.06,Graduate
4420,1,1.0,2.0,9773.0,1,1,120.0,105,1,1.0,...,0,6.0,6,2,11.000000,0,11.1,0.6,2.02,Dropout
4421,1,1.0,1.0,9500.0,1,1,154.0,1,37,37.0,...,0,8.0,9,1,13.500000,0,13.9,-0.3,0.79,Dropout
4422,1,1.0,1.0,9147.0,1,1,180.0,1,37,37.0,...,0,5.0,6,5,12.000000,0,9.4,-0.8,-3.12,Graduate
4423,1,10.0,1.0,9773.0,1,1,152.0,22,38,37.0,...,0,6.0,6,6,13.000000,0,12.7,3.7,-1.70,Graduate

I can see a spelling mistake with nationality so i fix the spelling error

In [12]:
df = df.rename(columns  = {"Nacionality": "Nationality"})

In [14]:
df

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nationality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17.0,5.0,171.0,1,1,122.0,1,19,12.0,...,0,0.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15.0,1.0,9254.0,1,1,160.0,1,1,3.0,...,0,6.0,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1.0,5.0,9070.0,1,1,122.0,1,37,37.0,...,0,6.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17.0,2.0,9773.0,1,1,122.0,1,38,37.0,...,0,6.0,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39.0,1.0,8014.0,0,1,100.0,1,37,38.0,...,0,6.0,6,6,13.000000,0,13.9,-0.3,0.79,Graduate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4419,1,1.0,6.0,9773.0,1,1,125.0,1,1,1.0,...,0,6.0,8,5,12.666667,0,15.5,2.8,-4.06,Graduate
4420,1,1.0,2.0,9773.0,1,1,120.0,105,1,1.0,...,0,6.0,6,2,11.000000,0,11.1,0.6,2.02,Dropout
4421,1,1.0,1.0,9500.0,1,1,154.0,1,37,37.0,...,0,8.0,9,1,13.500000,0,13.9,-0.3,0.79,Dropout
4422,1,1.0,1.0,9147.0,1,1,180.0,1,37,37.0,...,0,5.0,6,5,12.000000,0,9.4,-0.8,-3.12,Graduate
4423,1,10.0,1.0,9773.0,1,1,152.0,22,38,37.0,...,0,6.0,6,6,13.000000,0,12.7,3.7,-1.70,Graduate

Next I will see if there's any null values and will delete them

In [15]:
df.isnull().sum()

Marital status                                    0
Application mode                                  1
Application order                                 1
Course                                            3
Daytime/evening attendance                        0
Previous qualification                            0
Previous qualification (grade)                    4
Nationality                                       0
Mother's qualification                            0
Father's qualification                            1
Mother's occupation                               1
Father's occupation                               1
Admission grade                                   2
Displaced                                         0
Educational special needs                         0
Debtor                                            1
Tuition fees up to date                           1
Gender                                            0
Scholarship holder                                0
Age at enrollment                                 1
International                                     1
Curricular units 1st sem (credited)               0
Curricular units 1st sem (enrolled)               0
Curricular units 1st sem (evaluations)            0
Curricular units 1st sem (approved)               0
Curricular units 1st sem (grade)                  1
Curricular units 1st sem (without evaluations)    0
Curricular units 2nd sem (credited)               0
Curricular units 2nd sem (enrolled)               1
Curricular units 2nd sem (evaluations)            0
Curricular units 2nd sem (approved)               0
Curricular units 2nd sem (grade)                  1
Curricular units 2nd sem (without evaluations)    0
Unemployment rate                                 0
Inflation rate                                    0
GDP                                               0
Target                                            0
dtype: int64

In [6]:
df = df.dropna()

In [7]:
df.info()

<class 'pandas.DataFrame'>
Index: 4405 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4405 non-null   str
 1   Application mode                                4405 non-null   float64
 2   Application order                               4405 non-null   float64
 3   Course                                          4405 non-null   float64
 4   Daytime/evening attendance                      4405 non-null   int64
 5   Previous qualification                          4405 non-null   int64
 6   Previous qualification (grade)                  4405 non-null   float64
 7   Nacionality                                     4405 non-null   str
 8   Mother's qualification                          4405 non-null   int64
 9   Father's qualification                          4405 non-null   float64
 10  Mother's occupation                             4405 non-null   float64
 11  Father's occupation                             4405 non-null   str
 12  Admission grade                                 4405 non-null   float64
 13  Displaced                                       4405 non-null   str
 14  Educational special needs                       4405 non-null   int64
 15  Debtor                                          4405 non-null   float64
 16  Tuition fees up to date                         4405 non-null   str
 17  Gender                                          4405 non-null   int64
 18  Scholarship holder                              4405 non-null   int64
 19  Age at enrollment                               4405 non-null   str
 20  International                                   4405 non-null   float64
 21  Curricular units 1st sem (credited)             4405 non-null   str
 22  Curricular units 1st sem (enrolled)             4405 non-null   int64
 23  Curricular units 1st sem (evaluations)          4405 non-null   int64
 24  Curricular units 1st sem (approved)             4405 non-null   int64
 25  Curricular units 1st sem (grade)                4405 non-null   float64
 26  Curricular units 1st sem (without evaluations)  4405 non-null   int64
 27  Curricular units 2nd sem (credited)             4405 non-null   int64
 28  Curricular units 2nd sem (enrolled)             4405 non-null   float64
 29  Curricular units 2nd sem (evaluations)          4405 non-null   int64
 30  Curricular units 2nd sem (approved)             4405 non-null   int64
 31  Curricular units 2nd sem (grade)                4405 non-null   float64
 32  Curricular units 2nd sem (without evaluations)  4405 non-null   int64
 33  Unemployment rate                               4405 non-null   float64
 34  Inflation rate                                  4405 non-null   float64
 35  GDP                                             4405 non-null   float64
 36  Target                                          4405 non-null   str
dtypes: float64(15), int64(14), str(8)
memory usage: 1.3 MB

In [19]:
df.count()

Marital status                                    4405
Application mode                                  4405
Application order                                 4405
Course                                            4405
Daytime/evening attendance                        4405
Previous qualification                            4405
Previous qualification (grade)                    4405
Nationality                                       4405
Mother's qualification                            4405
Father's qualification                            4405
Mother's occupation                               4405
Father's occupation                               4405
Admission grade                                   4405
Displaced                                         4405
Educational special needs                         4405
Debtor                                            4405
Tuition fees up to date                           4405
Gender                                            4405
Scholarship holder                                4405
Age at enrollment                                 4405
International                                     4405
Curricular units 1st sem (credited)               4405
Curricular units 1st sem (enrolled)               4405
Curricular units 1st sem (evaluations)            4405
Curricular units 1st sem (approved)               4405
Curricular units 1st sem (grade)                  4405
Curricular units 1st sem (without evaluations)    4405
Curricular units 2nd sem (credited)               4405
Curricular units 2nd sem (enrolled)               4405
Curricular units 2nd sem (evaluations)            4405
Curricular units 2nd sem (approved)               4405
Curricular units 2nd sem (grade)                  4405
Curricular units 2nd sem (without evaluations)    4405
Unemployment rate                                 4405
Inflation rate                                    4405
GDP                                               4405
Target                                            4405
dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 4405 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4405 non-null   str
 1   Application mode                                4405 non-null   float64
 2   Application order                               4405 non-null   float64
 3   Course                                          4405 non-null   float64
 4   Daytime/evening attendance                      4405 non-null   int64
 5   Previous qualification                          4405 non-null   int64
 6   Previous qualification (grade)                  4405 non-null   float64
 7   Nacionality                                     4405 non-null   str
 8   Mother's qualification                          4405 non-null   int64
 9   Father's qualification                          4405 non-null   float64
 10  Mother's occupation                             4405 non-null   float64
 11  Father's occupation                             4405 non-null   str
 12  Admission grade                                 4405 non-null   float64
 13  Displaced                                       4405 non-null   str
 14  Educational special needs                       4405 non-null   int64
 15  Debtor                                          4405 non-null   float64
 16  Tuition fees up to date                         4405 non-null   str
 17  Gender                                          4405 non-null   int64
 18  Scholarship holder                              4405 non-null   int64
 19  Age at enrollment                               4405 non-null   str
 20  International                                   4405 non-null   float64
 21  Curricular units 1st sem (credited)             4405 non-null   str
 22  Curricular units 1st sem (enrolled)             4405 non-null   int64
 23  Curricular units 1st sem (evaluations)          4405 non-null   int64
 24  Curricular units 1st sem (approved)             4405 non-null   int64
 25  Curricular units 1st sem (grade)                4405 non-null   float64
 26  Curricular units 1st sem (without evaluations)  4405 non-null   int64
 27  Curricular units 2nd sem (credited)             4405 non-null   int64
 28  Curricular units 2nd sem (enrolled)             4405 non-null   float64
 29  Curricular units 2nd sem (evaluations)          4405 non-null   int64
 30  Curricular units 2nd sem (approved)             4405 non-null   int64
 31  Curricular units 2nd sem (grade)                4405 non-null   float64
 32  Curricular units 2nd sem (without evaluations)  4405 non-null   int64
 33  Unemployment rate                               4405 non-null   float64
 34  Inflation rate                                  4405 non-null   float64
 35  GDP                                             4405 non-null   float64
 36  Target                                          4405 non-null   str
dtypes: float64(15), int64(14), str(8)
memory usage: 1.3 MB

We can see dropping null values ,it has dropped from 4424 to 4405 rows, this isnt that big of a change to the data set so it is ok.
The overall characterisation of the data size is it has 37 columns including the target, with a mix of string, float and integer. The target is a string

AttributeError: 'Index' object has no attribute 'sum'